-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 08:43:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `KantineAppDB` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `KantineAppDB` DEFAULT CHARACTER SET utf8 ;
USE `KantineAppDB` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KantineAppDB`.`User` ;

CREATE TABLE IF NOT EXISTS `KantineAppDB`.`User` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `isPersonel` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KantineAppDB`.`Order` ;

CREATE TABLE IF NOT EXISTS `KantineAppDB`.`Order` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `orderTime` DATETIME NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `User_userId` INT NOT NULL,
  PRIMARY KEY (`orderId`),
  INDEX `fk_Order_User_idx` (`User_userId` ASC),
  CONSTRAINT `fk_Order_User`
    FOREIGN KEY (`User_userId`)
    REFERENCES `KantineAppDB`.`User` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KantineAppDB`.`Personel` ;

CREATE TABLE IF NOT EXISTS `KantineAppDB`.`Personel` (
  `personelId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`personelId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KantineAppDB`.`Items` ;

CREATE TABLE IF NOT EXISTS `KantineAppDB`.`Items` (
  `itemId` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(45) NOT NULL,
  `itemDescription` VARCHAR(45) NOT NULL,
  `itemPrice` INT NOT NULL,
  PRIMARY KEY (`itemId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order_has_Items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `KantineAppDB`.`Order_has_Items` ;

CREATE TABLE IF NOT EXISTS `KantineAppDB`.`Order_has_Items` (
  `Order_orderId` INT NOT NULL,
  `Items_itemId` INT NOT NULL,
  PRIMARY KEY (`Order_orderId`, `Items_itemId`),
  INDEX `fk_Order_has_Items_Items1_idx` (`Items_itemId` ASC),
  INDEX `fk_Order_has_Items_Order1_idx` (`Order_orderId` ASC),
  CONSTRAINT `fk_Order_has_Items_Order1`
    FOREIGN KEY (`Order_orderId`)
    REFERENCES `KantineAppDB`.`Order` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_has_Items_Items1`
    FOREIGN KEY (`Items_itemId`)
    REFERENCES `KantineAppDB`.`Items` (`itemId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
